version: "3.7"

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - media_volume:/usr/src/app/media/
      - static_volume:/usr/src/app/static/
    expose:
      - 8001
    env_file:
      - ./dockers/envs/.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dockers/envs/.env.prod.db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  nginx:
    build: ./dockers/nginx/prod
    volumes:
      - media_volume:/usr/src/app/media/
      - static_volume:/usr/src/app/static/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume:
  static_volume:
