# Generated by Django 3.0.10 on 2020-10-05 15:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading_title', models.CharField(blank=True, help_text='Описание главного заголовка Home-Page страницы блога', max_length=140)),
                ('heading_description', models.CharField(blank=True, help_text='Описание верхнего заголовка Home-Page страницы блога', max_length=255)),
                ('banner_angle_img', models.ForeignKey(help_text='Картинка 573х389 на главном header банере', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Страница: About',
                'verbose_name_plural': 'Страница: About',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
