# Generated by Django 3.0.10 on 2020-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='sub_banner_angle_img',
            field=models.FileField(null=True, upload_to='svg'),
        ),
    ]
