# Generated by Django 3.0.10 on 2020-10-05 16:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201005_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body_block',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
