# Generated by Django 3.0.10 on 2020-10-06 07:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading_title', models.CharField(blank=True, help_text='Описание главного заголовка Home-Page страницы блога', max_length=140)),
                ('body_block', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=True))]))], blank=True, null=True)),
                ('banner_angle_img', models.ForeignKey(help_text='Картинка 573х389 на главном header банере', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
                ('sub_banner_angle_img', models.ForeignKey(help_text='Мелкаий треугольник возле главного банера', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_sub_banner_angle_img', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Страница: Contact',
                'verbose_name_plural': 'Страница: Contact',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
