# Generated by Django 3.0.10 on 2020-09-29 19:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('tutorials', '0002_blogpostpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostpage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Страница с постом', 'verbose_name_plural': 'Страницы с постами'},
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='blog_preview_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='body_block',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True))])), ('code_block', wagtail.core.blocks.StructBlock([('code_text', wagtail.core.blocks.RichTextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='tutorials.BlogCategory'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='external_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
