# Generated by Django 3.0.10 on 2020-09-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200929_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='read_length',
            field=models.IntegerField(default=15, null=True),
        ),
    ]
