# Generated by Django 3.0.10 on 2020-09-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_blogpostpage_read_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistpage',
            old_name='subtitle',
            new_name='header_title_description',
        ),
        migrations.AddField(
            model_name='bloglistpage',
            name='header_title',
            field=models.CharField(default='Публикации и Посты', max_length=155, null=True),
        ),
    ]
