# Generated by Django 3.0.10 on 2020-10-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('tutorials', '0005_auto_20200930_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistpage',
            name='banner_angle_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
