# Generated by Django 3.0.10 on 2020-10-02 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('tutorials', '0006_bloglistpage_banner_angle_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistpage',
            name='sub_banner_angle_img',
            field=models.ForeignKey(help_text='Суб картинка (треугольник)Картинка 573х389 на главном header банере', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_list_page', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='bloglistpage',
            name='banner_angle_img',
            field=models.ForeignKey(help_text='Картинка 573х389 на главном header банере', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
