# Generated by Django 3.0.10 on 2020-10-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_auto_20201002_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistpage',
            name='sub_banner_angle_img',
            field=models.FileField(null=True, upload_to='svg'),
        ),
    ]
