# Generated by Django 3.0.10 on 2020-10-04 14:11

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_auto_20201002_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body_block',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True))])), ('code_block', wagtail.core.blocks.StructBlock([('code_text', wagtail.core.blocks.RichTextBlock(required=True))])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=True))])), ('img_block', wagtail.core.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock()), ('img_description', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='read_length',
            field=models.IntegerField(default=15, help_text='Длина чтения статьи', null=True),
        ),
    ]
