# Generated by Django 3.0.10 on 2020-10-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('tutorials', '0010_auto_20201004_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistpage',
            name='sub_banner_angle_img',
            field=models.ForeignKey(help_text='Мелкаий треугольник возле главного банера', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_banner_angle_img', to='wagtailimages.Image'),
        ),
    ]
