# Generated by Django 3.0.10 on 2020-10-06 04:29

import apps.stream_field.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_auto_20201005_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body_block',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True))])), ('code_block', apps.stream_field.blocks.CodeBlock()), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=True))])), ('img_block', wagtail.core.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock()), ('img_description', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
