# Generated by Django 3.0.10 on 2020-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_description',
            field=models.CharField(blank=True, help_text='Описание верхнего заголовка Home-Page страницы блога', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_title',
            field=models.CharField(blank=True, help_text='Описание главного заголовка Home-Page страницы блога', max_length=140),
        ),
    ]
